apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nffnd4jan-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nffnd4jan-java-quarkus-gitops